import type { Config } from "tailwindcss";
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    "text-blue-mid-light",
    "text-green-mid-light",
    "text-yellow-mid-light",
    "text-purple-mid-light",
    "text-orange-mid-light",
    "text-blue",
    "text-purple",
    "text-yellow",
    "text-green",
    "text-grey",
    "border-blue",
    "border-purple",
    "border-yellow",
    "border-green",
    "border-orange",
    "border-grey",
    "bg-blue",
    "bg-purple",
    "bg-yellow",
    "bg-green",
    "bg-grey",
    "bg-orange",
    "bg-red",
    "bg-blue-light",
    "bg-purple-light",
    "bg-yellow-light",
    "bg-green-light",
    "bg-grey-light",
    "bg-orange-light",
    "bg-red-light",
    "border-red",
  ],
  theme: {
    colors: {
      blue: "#0065BD",
      green: "#2FCF13",
      yellow: "#F0D60A",
      purple: "#8E00C7",
      orange: "#FD7024",
      white: "#ffffff",
      black: "#000000",
      grey: "#858585",
      red: "#f53f27",
      "blue-light": "#ECF6FF",
      "green-light": "#E9FFE5",
      "yellow-light": "#FFFBDF",
      "purple-light": "#FAECFF",
      "orange-light": "#FFDFCD",
      "grey-light": "#DDDDDD",
      "red-light": "#f7c7c1",
      "blue-dark": "#002341",
      "green-dark": "#10280C",
      "yellow-dark": "#423A00",
      "purple-dark": "#250033",
      "orange-dark": "#381A00",
      "grey-dark": "#454545",
      "blue-mid-light": "#A3D4FF",
      "green-mid-light": "#A5FF95",
      "yellow-mid-light": "#FFF184",
      "purple-mid-light": "#EFC2FF",
      "orange-mid-light": "#FFB38A",
      "blue-mid-dark": "#003B6F",
      "green-mid-dark": "#127900",
      "yellow-mid-dark": "#9E8D06",
      "purple-mid-dark": "#560077",
      "orange-mid-dark": "#852E00",
    },
    fontFamily: {
      sans: ["inter", "Arial", "sans-serif"],
    },
    extend: {},
  },
  plugins: [],
} satisfies Config;
