export type UserEvent = {
  id: string;
  name: string;
  picture: string;
  description: string;
  category: string;
  tags: string[];
  start_time: string;
  end_time: string;
  host: string;
  max_number_of_participants: number;
  min_number_of_participants: number;
  participants: number;
  longitude: number;
  latitude: number;
};

export const events: UserEvent[] = [
  {
    id: "1",
    name: "Basketball Game at Olympiapark",
    picture: "https://via.placeholder.com/150",
    description:
      "A friendly game of basketball at the Olympiapark courts. All skill levels welcome!",
    category: "Sport",
    tags: ["basketball", "outdoor", "friendly"],
    start_time: "2024-11-25T15:00:00",
    end_time: "2024-11-25T17:00:00",
    host: "John Doe",
    max_number_of_participants: 10,
    min_number_of_participants: 4,
    participants: 6,
    longitude: 11.55377,
    latitude: 48.17432,
  },
  {
    id: "2",
    name: "Tech Meetup: AI Trends",
    picture: "https://via.placeholder.com/150",
    description:
      "Discuss the latest trends in AI with fellow tech enthusiasts.",
    category: "Relax",
    tags: ["AI", "networking", "technology"],
    start_time: "2024-11-27T18:00:00",
    end_time: "2024-11-27T20:00:00",
    host: "Alice Müller",
    max_number_of_participants: 50,
    min_number_of_participants: 5,
    participants: 25,
    longitude: 11.5678,
    latitude: 48.1351,
  },
  {
    id: "3",
    name: "Munich Photography Walk",
    picture: "https://via.placeholder.com/150",
    description:
      "Explore Munich's iconic spots and take stunning photos with fellow photographers.",
    category: "Art",
    tags: ["photography", "walking", "networking"],
    start_time: "2024-11-26T14:00:00",
    end_time: "2024-11-26T16:00:00",
    host: "Clara Fischer",
    max_number_of_participants: 15,
    min_number_of_participants: 3,
    participants: 8,
    longitude: 11.57361,
    latitude: 48.14063,
  },
  {
    id: "4",
    name: "Cooking Class: Bavarian Dishes",
    picture: "https://via.placeholder.com/150",
    description:
      "Learn how to cook authentic Bavarian dishes with a professional chef.",
    category: "Food",
    tags: ["cooking", "Bavarian cuisine", "learning"],
    start_time: "2024-11-28T11:00:00",
    end_time: "2024-11-28T14:00:00",
    host: "Hans Schmidt",
    max_number_of_participants: 12,
    min_number_of_participants: 5,
    participants: 10,
    longitude: 11.54506,
    latitude: 48.14526,
  },
  {
    id: "5",
    name: "Yoga Session in the Park",
    picture: "https://via.placeholder.com/150",
    description:
      "Join us for a relaxing yoga session in the Englischer Garten.",
    category: "Nature",
    tags: ["yoga", "outdoor", "wellness"],
    start_time: "2024-11-24T09:00:00",
    end_time: "2024-11-24T10:30:00",
    host: "Sophie Braun",
    max_number_of_participants: 20,
    min_number_of_participants: 5,
    participants: 15,
    longitude: 11.60095,
    latitude: 48.16197,
  },
  {
    id: "6",
    name: "Basketball Match",
    picture: "https://example.com/basketball.jpg",
    description: "A friendly basketball game at the local park.",
    category: "Sport",
    tags: ["basketball", "outdoor", "fun"],
    start_time: "2024-11-24T15:00:00+01:00",
    end_time: "2024-11-24T17:00:00+01:00",
    host: "John Doe",
    max_number_of_participants: 10,
    min_number_of_participants: 2,
    participants: 6,
    longitude: 11.57549,
    latitude: 48.13743,
  },
  {
    id: "7",
    name: "Coding Workshop",
    picture: "https://example.com/coding.jpg",
    description: "Learn TypeScript and enhance your coding skills.",
    category: "Art",
    tags: ["coding", "typescript", "workshop"],
    start_time: "2024-11-25T10:00:00+01:00",
    end_time: "2024-11-25T12:00:00+01:00",
    host: "Alice Smith",
    max_number_of_participants: 20,
    min_number_of_participants: 5,
    participants: 12,
    longitude: 11.57392,
    latitude: 48.13512,
  },
  {
    id: "8",
    name: "Munich Photography Tour",
    picture: "https://example.com/phototour.jpg",
    description: "Explore Munich's beautiful landmarks through a camera lens.",
    category: "Art",
    tags: ["photography", "tour", "munich"],
    start_time: "2024-11-26T09:00:00+01:00",
    end_time: "2024-11-26T13:00:00+01:00",
    host: "Emma Müller",
    max_number_of_participants: 15,
    min_number_of_participants: 3,
    participants: 8,
    longitude: 11.58198,
    latitude: 48.14249,
  },
  {
    id: "9",
    name: "Yoga in the Park",
    picture: "https://example.com/yoga.jpg",
    description: "Join us for a relaxing yoga session in the English Garden.",
    category: "Relax",
    tags: ["yoga", "wellness", "outdoor"],
    start_time: "2024-11-27T08:00:00+01:00",
    end_time: "2024-11-27T09:30:00+01:00",
    host: "Sophia Becker",
    max_number_of_participants: 20,
    min_number_of_participants: 5,
    participants: 14,
    longitude: 11.60393,
    latitude: 48.15471,
  },
  {
    id: "10",
    name: "Board Games Night",
    picture: "https://example.com/boardgames.jpg",
    description:
      "Enjoy an evening of strategy and fun with classic board games.",
    category: "Relax",
    tags: ["games", "social", "indoor"],
    start_time: "2024-11-28T18:00:00+01:00",
    end_time: "2024-11-28T21:00:00+01:00",
    host: "Liam Johnson",
    max_number_of_participants: 8,
    min_number_of_participants: 2,
    participants: 4,
    longitude: 11.56836,
    latitude: 48.13379,
  },
];
